### ISSUE TITLE
Update clarity to latest stacks-blockchain

### ISSUE THREAD

**Issue by friedger** [blockstack/clarity-js-sdk#119]
I would like to use `contract-of` in my contract and use unit tests. Currently, it fails due with `UnknownFunction(contract-of)`

Related to #99

**Comment by friedger** [comment]
Depends on https://github.com/blockstack/stacks-blockchain/pull/1949

**Comment by friedger** [comment]
The current version does not support strings.

**Comment by friedger** [comment]
Related to https://github.com/blockstack/stacks-transactions-js/issues/117

**Comment by njordhov** [comment]
Related: The Clarity REPL is also not up to par: https://lgalabru.github.io/clarity-repl/

**Comment by friedger** [comment]
Trying to update locally:

Trying to update locally:

`BLOCKSTACK_CORE_SOURCE_BRANCH="master" npm  install`

Resulting in 
```
error: multiple packages with binaries found: bitcoin-neon-controller, blockstack-core, stacks-node
Cargo build failed with exit code 101
child_process.js:637
    throw err;
    ^

Error: Command failed: npx ts-node@^8.2.0 --project /home/friedger/_repos/github/blockstack/clarity-js-sdk/packages/clarity-native-bin/tsconfig.build.json /home/friedger/_repos/github/blockstack/clarity-js-sdk/packages/clarity-native-bin/src/directInstall.ts
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at tsNodeInstall (/home/friedger/_repos/github/blockstack/clarity-js-sdk/packages/clarity-native-bin/postInstallScript.js:57:16)
```

What needs to be done?

**Comment by CharlieC3** [comment]
@friedger 
Running `BLOCKSTACK_CORE_SOURCE_BRANCH="master" npm install` should now work with the latest commit to `master`.
