### ISSUE TITLE
Updating clarity-cli

### ISSUE THREAD

**Issue by lgalabru** [blockstack/clarity-js-sdk#126]
We merged a bunch of non-backward compatible features / fixes recently, and working with this lib became a bit tedious.
@zone117x @hstove what is the flow for updating the clarity-cli binary that powers that lib?

**Comment by zone117x** [comment]
@CharlieC3 recently made some big improvements to this in these PRs
* https://github.com/blockstack/clarity-js-sdk/pull/122
* https://github.com/blockstack/clarity-js-sdk/pull/124

Looks like you just need to update `const CORE_SDK_TAG = "v23.0.0.12-krypton";`

**Comment by CharlieC3** [comment]
> Looks like you just need to update const CORE_SDK_TAG = "v23.0.0.12-krypton";

Not even! Just cut a new release in the `stacks-blockchain` repo and a new branch will be cut in this repo with the change, and a PR will be auto-created. Once merged, it'll auto-version this project and auto-publish it.
