### ISSUE TITLE
Tests of generated `hello world` project fails silently

### ISSUE THREAD

**Issue by LNow** [blockstack/clarity-js-sdk#197]
When a new `hello world` project is created, the tests fails with `Error: Unable to unwrap result: (ok "hello world")` as it tries to unwrap UTF8 string that is not encoded at all.
https://github.com/blockstack/clarity-js-sdk/blob/80c912b37dcf7dd9737bc640d28c59fe3bc87fe5/packages/generator-clarity-dev/generators/app/templates/test/hello-world.ts_template#L25
https://github.com/blockstack/clarity-js-sdk/blob/80c912b37dcf7dd9737bc640d28c59fe3bc87fe5/packages/generator-clarity-dev/generators/app/templates/contracts/hello-world.clar#L1-L2

Although test is failing, it is not caught by the main test suite.

**Comment by LNow** [comment]
I have a dilemma with this one... We can

- change contract and make it return utf8 string
```
 (define-public (say-hi) 
    (ok u"hello world")) 
```

- change test and verifies in it if contract returns string that is not encoded
```
 const result = Result.unwrapString(receipt, "");
```


I was also thinking about making `unwrapString`  `encoding` parameter optional, and making its default value empty instead of `hex` as it is right now.
It should make interface of this function much cleaner for the end user, but it would be a BC change.

**Comment by agraebe** [comment]
would you be able to draft up a PR based on your suggestions for the test/contract improvements @LNow ?
