### ISSUE TITLE
Contract interface type declaration generation

### ISSUE THREAD

**Issue by zone117x** [blockstack/clarity-js-sdk#30]
Use the contract interface spec to generate a typescript `d.ts` type declarations for workspace Clarity contracts. 

The Typescript interfaces should be compatible (able to cast over) a contract-proxy instance (described in https://github.com/blockstack/clarity-js-sdk/issues/28).

**Comment by agraebe** [comment]
is this covered by https://github.com/obylabs/clarigen ?
