### ISSUE TITLE
Determine contract dependency resolution strategy

### ISSUE THREAD

**Issue by zone117x** [blockstack/clarity-js-sdk#31]
How should deployment-order (dependency trees) be determined, given a directory of clarity smart contracts with inter-dependencies? 

Possible methods:
* Explicitly defined migrations/deployments file. 
* SDK brute-forces / iterates through deployment attempts, using contract name reference error. 
* Clarity rust CLI command that can receive a bundle of contract sources and return back the dependency tree (this partially just pushes the problem to the rust codebase). 

Use case:
Dev-UX with a future vscode extension that provides typed contract definitions for all available workspace clarity contracts. Note: this feature would probably start off as a manually invoked script.

**Comment by agraebe** [comment]
I wonder if this should be closed - with Clarinet, there's a config file that allows devs to set dependencies for contracts
