### ISSUE TITLE
OptionalType check

### ISSUE THREAD

**Issue by friedger** [blockstack/clarity-js-sdk#42]
Currently, I need to explicitly convert an optional type to its original type even though the variable can’t be optional in that branch.

```
(if (not (is-none? price))
      (contract-call! token transfer receiver (expects! price invalid-price-err))
      invalid-price-err
)
```

Is it possible to deduce that in this case price is a real type, not an optional one? So that I can remove the `expects!` method.

**Comment by zone117x** [comment]
Issue moved to [blockstack/blockstack-core #1080](https://github.com/blockstack/blockstack-core/issues/1080) via [**ZenHub**](https://www.zenhub.com/)
