### ISSUE TITLE
Improve README (main + packages)

### ISSUE THREAD

**Issue by lgalabru** [blockstack/clarity-js-sdk#6]
- [ ] Add fancy badges
- [ ] Give some context about clarity, its mission, blockstack-core, etc.
- [x] Document learna commands
- [ ] Default template for the README in the packages

**Comment by moxiegirl** [comment]
[] Contributors guide
[] Building checklist

**Comment by zone117x** [comment]
Marked a few items from lists as done -- see referenced PRs.
