### ISSUE TITLE
"true" and  "false" not recognized

### ISSUE THREAD

**Issue by friedger** [blockstack/clarity-js-sdk#71]
Adding a line like `(and true false)` to a contract let the test fail with
```
UndefinedVariable("true")
```

**Comment by friedger** [comment]
clartiy-sdk-0.0.8 does not contain the changes from https://github.com/blockstack/stacks-blockchain/commit/a51658cd2079d6594c7a48da6bd170254e568625

**Comment by zone117x** [comment]
Working publishing updated binaries now

**Comment by zone117x** [comment]
This is fixed in https://github.com/blockstack/clarity-js-sdk/pull/73 
(the `create-clarity-starter` packages has a permission issue and is pending publish cc @hstove)
