### ISSUE TITLE
Support initial stx balance

### ISSUE THREAD

**Issue by friedger** [blockstack/clarity-js-sdk#77]
Currently, the VM is started with 0 balance for all accounts. (I think)

For tests, it would be beneficial if the initial balance could be set.

**Comment by psq** [comment]
Now that `clarity-cli` supports setting initial balances via a json file (see https://github.com/blockstack/stacks-blockchain/pull/1662), the sdk should allow you to either pass your own JSON file, or provide an API to generate that JSON file when calling the `initialize` target on `clarity-cli`.

JSON file should look like:
```JSON
[
  {
    "principal": "S1G2081040G2081040G2081040G208105NK8PE5",
    "amount": 1000
  },
  {
    "principal": "S1G2081040G2081040G2081040G208105NK8PE5.names",
    "amount": 2000
  } 
]
```
Usage:
```bash
clarity-cli balances.json path-to-db
```

**Comment by friedger** [comment]
What should the API look like? 

I suggest that each provider (`NativeClarityBinProvider`, `JsonRpcProvider`, ..) handles their own initialization process. Users have then to register their provider manually.
