### ISSUE TITLE
Implement JSONRcp provider

### ISSUE THREAD

**Issue by friedger** [blockstack/clarity-js-sdk#82]
There is a skelecton for a json rcp provider: https://github.com/blockstack/clarity-js-sdk/blob/master/packages/clarity/src/providers/jsonRpc/index.ts

stacks-transaction-js could fulfill most of the required methods.

What is the plan here? Does it make sense?

**Comment by hstove** [comment]
Hey Friedger - I think we'll want to implement such a provider at some point, but if you asked me, we should be figuring out a solution that can support `clarity-cli` (which exists), as well as RPC (what you're saying), but also via Connect. Ideally some identical API would be great, but there would be a lot of abstraction needed.

**Comment by friedger** [comment]
Connect Provider and the jsonrcp do the same thing: talking to the node api.

What would be the difference between the two?

Have you had a look at the PR?
