### ISSUE TITLE
Clarity-starter: Document `counter.ts`

### ISSUE THREAD

**Issue by agraebe** [blockstack/clarity-js-sdk#95]
The Counter tutorial asks developers to review the file. However, it seems a bit difficult to follow. Documentation could help

**Comment by njordhov** [comment]
The counter example could be improved by changing the `increment` and `decrement` functions to only get the counter value once before setting it:

```clojure
(define-public (increment)
   (let ((value (+ (var-get counter) 1)))
      (var-set counter value)
      (ok value)))
```

Also, the trailing parens are placed on the same line per Lisp conventions. This is a replacement for:

```clojure
(define-public (increment)
   (begin
      (var-set counter (+ (var-get counter) 1))
      (ok (var-get counter))
   )
)
```

**Comment by agraebe** [comment]
I like that it makes the implementation more efficient and introduces developers to `let` and `value`. 

cc @johndmulhausen
