### ISSUE TITLE
Automate `clarity-native-bin` updates

### ISSUE THREAD

**Issue by kantai** [blockstack/clarity-js-sdk#99]
The way that `clarity-native-bin` currently works is roughly as follows:

1. We have automated builds on `stacks-blockchain`, which can produce the necessary binary outputs.
2. Those binary outputs need to be zipped, tarballed, what-have-you (and marked executable)
3. Those files need to uploaded as release artifacts to a release on this repo `clarity-js-sdk`
4. The file `packages/clarity-native-bin/src/index.ts` needs to be updated with the new release tag
5. This needs to be pushed to `npm`

This process is pretty cumbersome and it leads to the situation we're currently in with out of date binaries.

Steps 1-3 could be automated on the `stacks-blockchain` repo pretty easily by just publishing those release binaries on the stacks-blockchain's repo, rather than here. That would mean updating this line (https://github.com/blockstack/clarity-js-sdk/blob/master/packages/clarity-native-bin/src/fetchDist.ts#L12).

Steps 4 and 5 could be eliminated if we just had the `clarity-native-bin` always fetch the latest tag. However, I think that's a decision for the dev-x team as to whether or not we want the `clarity-native-bin` package to default to always pulling the latest _or_ being pinned to a version.

**Comment by hstove** [comment]
> Steps 4 and 5 could be eliminated if we just had the clarity-native-bin always fetch the latest tag. However, I think that's a decision for the dev-x team as to whether or not we want the clarity-native-bin package to default to always pulling the latest or being pinned to a version.

Using the latest feels simple, but I think it would be against any SemVer principles. You could have your unit tests work one day and break the next, without changing anything.

_If_ we had releases on the `stacks-blockchain` repo, I think it would be straightforward to have an action in this repo that only runs on new releases in `stacks-blockchain`. That action would fetch the latest release, get its tag, and then automatically update internal files and publish a new release.

**Comment by kantai** [comment]
Sounds good to me, I'll ping back on this issue once we have releases on the `stacks-blockchain` repo set up.

**Comment by diwakergupta** [comment]
> Sounds good to me, I'll ping back on this issue once we have releases on the `stacks-blockchain` repo set up.

cc/ @CharlieC3 -- seems related to releases on stacks-blockchain https://github.com/blockstack/stacks-blockchain/issues/1780

**Comment by CharlieC3** [comment]
@diwakergupta I'm not sure how to continue on #1780 without more feedback on the issue, as any decisions regarding semantic versioning and automatic releases can have an impact on how the GH Action workflow operates.

**Comment by zone117x** [comment]
> Steps 4 and 5 could be eliminated if we just had the clarity-native-bin always fetch the latest tag. However, I think that's a decision for the dev-x team as to whether or not we want the clarity-native-bin package to default to always pulling the latest or being pinned to a version.

IMO it should not fetch latest. Historically there have been breaking changes pretty consistently.

**Comment by zone117x** [comment]
What I'd like to see is a setup where:
1. This repo is a set tag/version for the clarity-cli binary pulled from a stacks-blockchain release.
2. When a new version is released in the stacks-blockchain, a bot opens a PR to this repo which bumps that tag (kinda like dependabot).
3. Any of us can merge if the tests pass.

**Comment by CharlieC3** [comment]
Once https://github.com/blockstack/stacks-blockchain/issues/1780 is completed we can move onto hooking this up, it should be rather easy.

**Comment by diwakergupta** [comment]
> Once [blockstack/stacks-blockchain#1780](https://github.com/blockstack/stacks-blockchain/issues/1780) is completed we can move onto hooking this up, it should be rather easy.

@CharlieC3 now that above has been addressed, perhaps we can revisit this? Should help us avoid issues like #119 cc/ @agraebe

**Comment by CharlieC3** [comment]
@diwakergupta Sure, I'll find time for it after any high priority issues for mainnet are completed.

**Comment by friedger** [comment]
If developers have hard times to build and create clarity programs there is no need for mainnet...

**Comment by zone117x** [comment]
> However, I think that's a decision for the dev-x team as to whether or not we want the clarity-native-bin package to default to always pulling the latest or being pinned to a version.

I'd be in favor if pulling latest _if_ we can configure this repo configured to run nightly builds/tests to detect breaking changes.
